#!/busybox sh

/busybox mkdir -p /bin
/busybox cp /busybox /bin/busybox
/bin/busybox --install -s /bin
export PATH=/bin

mkdir -p /proc /sys /dev /tmp
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
mount -t tmpfs tmpfs /tmp

echo "tiny" > /proc/sys/kernel/hostname

echo 4 > /proc/sys/kernel/printk

printf "\n"
printf "\n"
printf "\033[1;34mWelcome to Mauri870's Linux Playground!\nHave fun exploring a minimal Linux system in your browser :)\033[0m\n"
printf "\n"
printf "\033[0;37mType \033[1;36mcat README\033[0;37m to learn more.\033[0m\n"
printf "\033[0;37mSource code: https://github.com/mauri870/tiny-linux\033[0m\n"
printf "\n"
printf "\033[1;33m  Kernel   :\033[0m \033[1;32m%s\033[0m\n" "$(cat /proc/version)"
printf "\033[1;33m  Userspace:\033[0m \033[1;32m%s\033[0m\n" "$(busybox | head -1)"
printf "\033[1;33m  Machine  :\033[0m \033[1;32m%s\033[0m\n" "$(uname -m)"
printf "\033[1;33m  Uptime   :\033[0m \033[1;32m%s\033[0m\n" "$(uptime | sed 's/.*up //' | sed 's/,.*//')"
printf "\033[1;33m  Memory   :\033[0m \033[1;32m%s\033[0m\n" "$(free -h | sed -n 's/^Mem:\s*\([^ ]*\)\s*\([^ ]*\).*/\2 used \/ \1 total/p')"

while true; do sh; done
