#!/busybox sh

/busybox mkdir -p /bin
/busybox cp /busybox /bin/busybox
/bin/busybox --install -s /bin
export PATH=/bin

mkdir -p /proc /sys /dev
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

echo "tiny" > /proc/sys/kernel/hostname

echo 4 > /proc/sys/kernel/printk

printf "\n"
printf "\n"
printf "\033[1;34mWelcome to Mauri870's Linux Emulator!\nHave fun exploring a minimal Linux distro in your browser :)\033[0m\n"
printf "\n"
printf "\033[0;37mType \033[1;36mcat README\033[0;37m to learn more.\033[0m\n"
printf "\n"
printf "\033[1;33m  Kernel   :\033[0m \033[1;32m%s\033[0m\n" "$(uname -a)"
printf "\033[1;33m  Userspace:\033[0m \033[1;32m%s\033[0m\n" "$(busybox | head -1)"
printf "\033[1;33m  Machine  :\033[0m \033[1;32m%s\033[0m\n" "$(uname -m)"
printf "\033[1;33m  Uptime   :\033[0m \033[1;32m%s\033[0m\n" "$(uptime | sed 's/.*up //' | sed 's/,.*//')"
printf "\033[1;33m  Memory   :\033[0m \033[1;32m%s\033[0m\n" "$(free -h | awk '/^Mem:/{print $3 " used / " $2 " total"}')"

while true; do sh; done